export const countries = [
    { "name": "Afganistán", "flagEmoji": "🇦🇫" },
    { "name": "Albania", "flagEmoji": "🇦🇱" },
    { "name": "Alemania", "flagEmoji": "🇩🇪" },
    { "name": "Andorra", "flagEmoji": "🇦🇩" },
    { "name": "Angola", "flagEmoji": "🇦🇴" },
    { "name": "Anguila", "flagEmoji": "🇦🇮" },
    { "name": "Antártida", "flagEmoji": "🇦🇶" },
    { "name": "Antigua y Barbuda", "flagEmoji": "🇦🇬" },
    { "name": "Antillas Holandesas", "flagEmoji": "🇧🇶" },
    { "name": "Arabia Saudita", "flagEmoji": "🇸🇦" },
    { "name": "Argelia", "flagEmoji": "🇩🇿" },
    { "name": "Argentina", "flagEmoji": "🇦🇷" },
    { "name": "Armenia", "flagEmoji": "🇦🇲" },
    { "name": "Aruba", "flagEmoji": "🇦🇼" },
    { "name": "Australia", "flagEmoji": "🇦🇺" },
    { "name": "Austria", "flagEmoji": "🇦🇹" },
    { "name": "Azerbaiyán", "flagEmoji": "🇦🇿" },
    { "name": "Bahamas", "flagEmoji": "🇧🇸" },
    { "name": "Bahrein", "flagEmoji": "🇧🇭" },
    { "name": "Bangladesh", "flagEmoji": "🇧🇩" },
    { "name": "Barbados", "flagEmoji": "🇧🇧" },
    { "name": "Bélgica", "flagEmoji": "🇧🇪" },
    { "name": "Belice", "flagEmoji": "🇧🇿" },
    { "name": "Benín", "flagEmoji": "🇧🇯" },
    { "name": "Bhután", "flagEmoji": "🇧🇹" },
    { "name": "Bielorrusia", "flagEmoji": "🇧🇾" },
    { "name": "Birmania", "flagEmoji": "🇲🇲" },
    { "name": "Bolivia", "flagEmoji": "🇧🇴" },
    { "name": "Bosnia y Herzegovina", "flagEmoji": "🇧🇦" },
    { "name": "Botsuana", "flagEmoji": "🇧🇼" },
    { "name": "Brasil", "flagEmoji": "🇧🇷" },
    { "name": "Brunéi", "flagEmoji": "🇧🇳" },
    { "name": "Bulgaria", "flagEmoji": "🇧🇬" },
    { "name": "Burkina Faso", "flagEmoji": "🇧🇫" },
    { "name": "Burundi", "flagEmoji": "🇧🇮" },
    { "name": "Cabo Verde", "flagEmoji": "🇨🇻" },
    { "name": "Camboya", "flagEmoji": "🇰🇭" },
    { "name": "Camerún", "flagEmoji": "🇨🇲" },
    { "name": "Canadá", "flagEmoji": "🇨🇦" },
    { "name": "Chad", "flagEmoji": "🇹🇩" },
    { "name": "Chile", "flagEmoji": "🇨🇱" },
    { "name": "China", "flagEmoji": "🇨🇳" },
    { "name": "Chipre", "flagEmoji": "🇨🇾" },
    { "name": "Ciudad del Vaticano", "flagEmoji": "🇻🇦" },
    { "name": "Colombia", "flagEmoji": "🇨🇴" },
    { "name": "Comoras", "flagEmoji": "🇰🇲" },
    { "name": "Corea del Norte", "flagEmoji": "🇰🇵" },
    { "name": "Corea del Sur", "flagEmoji": "🇰🇷" },
    { "name": "Costa de Marfil", "flagEmoji": "🇨🇮" },
    { "name": "Costa Rica", "flagEmoji": "🇨🇷" },
    { "name": "Croacia", "flagEmoji": "🇭🇷" },
    { "name": "Cuba", "flagEmoji": "🇨🇺" },
    { "name": "Dinamarca", "flagEmoji": "🇩🇰" },
    { "name": "Dominica", "flagEmoji": "🇩🇲" },
    { "name": "Ecuador", "flagEmoji": "🇪🇨" },
    { "name": "Egipto", "flagEmoji": "🇪🇬" },
    { "name": "El Salvador", "flagEmoji": "🇸🇻" },
    { "name": "Emiratos Árabes Unidos", "flagEmoji": "🇦🇪" },
    { "name": "Eritrea", "flagEmoji": "🇪🇷" },
    { "name": "Eslovaquia", "flagEmoji": "🇸🇰" },
    { "name": "Eslovenia", "flagEmoji": "🇸🇮" },
    { "name": "España", "flagEmoji": "🇪🇸" },
    { "name": "Estados Unidos de América", "flagEmoji": "🇺🇸" },
    { "name": "Estonia", "flagEmoji": "🇪🇪" },
    { "name": "Etiopía", "flagEmoji": "🇪🇹" },
    { "name": "Filipinas", "flagEmoji": "🇵🇭" },
    { "name": "Finlandia", "flagEmoji": "🇫🇮" },
    { "name": "Fiyi", "flagEmoji": "🇫🇯" },
    { "name": "Francia", "flagEmoji": "🇫🇷" },
    { "name": "Gabón", "flagEmoji": "🇬🇦" },
    { "name": "Gambia", "flagEmoji": "🇬🇲" },
    { "name": "Georgia", "flagEmoji": "🇬🇪" },
    { "name": "Ghana", "flagEmoji": "🇬🇭" },
    { "name": "Gibraltar", "flagEmoji": "🇬🇮" },
    { "name": "Granada", "flagEmoji": "🇬🇩" },
    { "name": "Grecia", "flagEmoji": "🇬🇷" },
    { "name": "Groenlandia", "flagEmoji": "🇬🇱" },
    { "name": "Guadalupe", "flagEmoji": "🇬🇵" },
    { "name": "Guam", "flagEmoji": "🇬🇺" },
    { "name": "Guatemala", "flagEmoji": "🇬🇹" },
    { "name": "Guayana Francesa", "flagEmoji": "🇬🇫" },
    { "name": "Guernsey", "flagEmoji": "🇬🇬" },
    { "name": "Guinea", "flagEmoji": "🇬🇳" },
    { "name": "Guinea Ecuatorial", "flagEmoji": "🇬🇶" },
    { "name": "Guinea-Bissau", "flagEmoji": "🇬🇼" },
    { "name": "Guyana", "flagEmoji": "🇬🇾" },
    { "name": "Haití", "flagEmoji": "🇭🇹" },
    { "name": "Honduras", "flagEmoji": "🇭🇳" },
    { "name": "Hong Kong", "flagEmoji": "🇭🇰" },
    { "name": "Hungría", "flagEmoji": "🇭🇺" },
    { "name": "India", "flagEmoji": "🇮🇳" },
    { "name": "Indonesia", "flagEmoji": "🇮🇩" },
    { "name": "Irak", "flagEmoji": "🇮🇶" },
    { "name": "Irán", "flagEmoji": "🇮🇷" },
    { "name": "Irlanda", "flagEmoji": "🇮🇪" },
    { "name": "Isla de Man", "flagEmoji": "🇮🇲" },
    { "name": "Isla de Navidad", "flagEmoji": "🇨🇽" },
    { "name": "Isla Norfolk", "flagEmoji": "🇳🇫" },
    { "name": "Islandia", "flagEmoji": "🇮🇸" },
    { "name": "Islas Caimán", "flagEmoji": "🇰🇾" },
    { "name": "Islas Cook", "flagEmoji": "🇨🇰" },
    { "name": "Islas Feroe", "flagEmoji": "🇫🇴" },
    { "name": "Islas Georgias del Sur y Sandwich del Sur", "flagEmoji": "🇬🇸" },
    { "name": "Islas Maldivas", "flagEmoji": "🇲🇻" },
    { "name": "Islas Malvinas", "flagEmoji": "🇫🇰" },
    { "name": "Islas Marianas del Norte", "flagEmoji": "🇲🇵" },
    { "name": "Islas Marshall", "flagEmoji": "🇲🇭" },
    { "name": "Islas Pitcairn", "flagEmoji": "🇵🇳" },
    { "name": "Islas Salomón", "flagEmoji": "🇸🇧" },
    { "name": "Islas Turcas y Caicos", "flagEmoji": "🇹🇨" },
    { "name": "Islas Ultramarinas Menores de Estados Unidos", "flagEmoji": "🇺🇲" },
    { "name": "Islas Vírgenes Británicas", "flagEmoji": "🇻🇬" },
    { "name": "Islas Vírgenes de los Estados Unidos", "flagEmoji": "🇻🇮" },
    { "name": "Israel", "flagEmoji": "🇮🇱" },
    { "name": "Italia", "flagEmoji": "🇮🇹" },
    { "name": "Jamaica", "flagEmoji": "🇯🇲" },
    { "name": "Japón", "flagEmoji": "🇯🇵" },
    { "name": "Jersey", "flagEmoji": "🇯🇪" },
    { "name": "Jordania", "flagEmoji": "🇯🇴" },
    { "name": "Kazajistán", "flagEmoji": "🇰🇿" },
    { "name": "Kenia", "flagEmoji": "🇰🇪" },
    { "name": "Kirguistán", "flagEmoji": "🇰🇬" },
    { "name": "Kiribati", "flagEmoji": "🇰🇮" },
    { "name": "Kuwait", "flagEmoji": "🇰🇼" },
    { "name": "Laos", "flagEmoji": "🇱🇦" },
    { "name": "Lesoto", "flagEmoji": "🇱🇸" },
    { "name": "Letonia", "flagEmoji": "🇱🇻" },
    { "name": "Líbano", "flagEmoji": "🇱🇧" },
    { "name": "Liberia", "flagEmoji": "🇱🇷" },
    { "name": "Libia", "flagEmoji": "🇱🇾" },
    { "name": "Liechtenstein", "flagEmoji": "🇱🇮" },
    { "name": "Lituania", "flagEmoji": "🇱🇹" },
    { "name": "Luxemburgo", "flagEmoji": "🇱🇺" },
    { "name": "Macao", "flagEmoji": "🇲🇴" },
    { "name": "Madagascar", "flagEmoji": "🇲🇬" },
    { "name": "Malasia", "flagEmoji": "🇲🇾" },
    { "name": "Malaui", "flagEmoji": "🇲🇼" },
    { "name": "Mali", "flagEmoji": "🇲🇱" },
    { "name": "Malta", "flagEmoji": "🇲🇹" },
    { "name": "Marruecos", "flagEmoji": "🇲🇦" },
    { "name": "Martinica", "flagEmoji": "🇲🇶" },
    { "name": "Mauricio", "flagEmoji": "🇲🇺" },
    { "name": "Mauritania", "flagEmoji": "🇲🇷" },
    { "name": "Mayotte", "flagEmoji": "🇾🇹" },
    { "name": "México", "flagEmoji": "🇲🇽" },
    { "name": "Micronesia", "flagEmoji": "🇫🇲" },
    { "name": "Moldavia", "flagEmoji": "🇲🇩" },
    { "name": "Mónaco", "flagEmoji": "🇲🇨" },
    { "name": "Mongolia", "flagEmoji": "🇲🇳" },
    { "name": "Montenegro", "flagEmoji": "🇲🇪" },
    { "name": "Montserrat", "flagEmoji": "🇲🇸" },
    { "name": "Mozambique", "flagEmoji": "🇲🇿" },
    { "name": "Namibia", "flagEmoji": "🇳🇦" },
    { "name": "Nauru", "flagEmoji": "🇳🇷" },
    { "name": "Nepal", "flagEmoji": "🇳🇵" },
    { "name": "Nicaragua", "flagEmoji": "🇳🇮" },
    { "name": "Níger", "flagEmoji": "🇳🇪" },
    { "name": "Nigeria", "flagEmoji": "🇳🇬" },
    { "name": "Niue", "flagEmoji": "🇳🇺" },
    { "name": "Noruega", "flagEmoji": "🇳🇴" },
    { "name": "Nueva Caledonia", "flagEmoji": "🇳🇨" },
    { "name": "Nueva Zelanda", "flagEmoji": "🇳🇿" },
    { "name": "Omán", "flagEmoji": "🇴🇲" },
    { "name": "Países Bajos", "flagEmoji": "🇳🇱" },
    { "name": "Pakistán", "flagEmoji": "🇵🇰" },
    { "name": "Palestina", "flagEmoji": "🇵🇸" },
    { "name": "Panamá", "flagEmoji": "🇵🇦" },
    { "name": "Papúa Nueva Guinea", "flagEmoji": "🇵🇬" },
    { "name": "Paraguay", "flagEmoji": "🇵🇾" },
    { "name": "Perú", "flagEmoji": "🇵🇪" },
    { "name": "Polinesia Francesa", "flagEmoji": "🇵🇫" },
    { "name": "Polonia", "flagEmoji": "🇵🇱" },
    { "name": "Portugal", "flagEmoji": "🇵🇹" },
    { "name": "Puerto Rico", "flagEmoji": "🇵🇷" },
    { "name": "Qatar", "flagEmoji": "🇶🇦" },
    { "name": "Reino Unido", "flagEmoji": "🇬🇧" },
    { "name": "República Centroafricana", "flagEmoji": "🇨🇫" },
    { "name": "República Checa", "flagEmoji": "🇨🇿" },
    { "name": "República de Macedonia", "flagEmoji": "🇲🇰" },
    { "name": "República del Congo", "flagEmoji": "🇨🇬" },
    { "name": "República Democrática del Congo", "flagEmoji": "🇨🇩" },
    { "name": "República Dominicana", "flagEmoji": "🇩🇴" },
    { "name": "Reunión", "flagEmoji": "🇷🇪" },
    { "name": "Ruanda", "flagEmoji": "🇷🇼" },
    { "name": "Rumanía", "flagEmoji": "🇷🇴" },
    { "name": "Rusia", "flagEmoji": "🇷🇺" },
    { "name": "Samoa", "flagEmoji": "🇼🇸" },
    { "name": "Samoa Americana", "flagEmoji": "🇦🇸" },
    { "name": "San Bartolomé", "flagEmoji": "🇧🇱" },
    { "name": "San Cristóbal y Nieves", "flagEmoji": "🇰🇳" },
    { "name": "San Marino", "flagEmoji": "🇸🇲" },
    { "name": "San Martín", "flagEmoji": "🇸🇽" },
    { "name": "San Pedro y Miquelón", "flagEmoji": "🇵🇲" },
    { "name": "San Vicente y las Granadinas", "flagEmoji": "🇻🇨" },
    { "name": "Santa Elena", "flagEmoji": "🇸🇭" },
    { "name": "Santa Lucía", "flagEmoji": "🇱🇨" },
    { "name": "Santo Tomé y Príncipe", "flagEmoji": "🇸🇹" },
    { "name": "Senegal", "flagEmoji": "🇸🇳" },
    { "name": "Serbia", "flagEmoji": "🇷🇸" },
    { "name": "Seychelles", "flagEmoji": "🇸🇨" },
    { "name": "Sierra Leona", "flagEmoji": "🇸🇱" },
    { "name": "Singapur", "flagEmoji": "🇸🇬" },
    { "name": "Sint Eustatius", "flagEmoji": "🇧🇶" },
    { "name": "Sint Maarten", "flagEmoji": "🇸🇽" },
    { "name": "Siria", "flagEmoji": "🇸🇾" },
    { "name": "Somalia", "flagEmoji": "🇸🇴" },
    { "name": "Sri Lanka", "flagEmoji": "🇱🇰" },
    { "name": "Suazilandia", "flagEmoji": "🇸🇿" },
    { "name": "Sudáfrica", "flagEmoji": "🇿🇦" },
    { "name": "Sudán", "flagEmoji": "🇸🇩" },
    { "name": "Sudán del Sur", "flagEmoji": "🇸🇸" },
    { "name": "Suecia", "flagEmoji": "🇸🇪" },
    { "name": "Suiza", "flagEmoji": "🇨🇭" },
    { "name": "Surinam", "flagEmoji": "🇸🇷" },
    { "name": "Svalbard y Jan Mayen", "flagEmoji": "🇸🇯" },
    { "name": "Tailandia", "flagEmoji": "🇹🇭" },
    { "name": "Taiwán", "flagEmoji": "🇹🇼" },
    { "name": "Tanzania", "flagEmoji": "🇹🇿" },
    { "name": "Tayikistán", "flagEmoji": "🇹🇯" },
    { "name": "Territorio Británico del Océano Índico", "flagEmoji": "🇮🇴" },
    { "name": "Territorios Australes Franceses", "flagEmoji": "🇹🇫" },
    { "name": "Timor Oriental", "flagEmoji": "🇹🇱" },
    { "name": "Togo", "flagEmoji": "🇹🇬" },
    { "name": "Tokelau", "flagEmoji": "🇹🇰" },
    { "name": "Tonga", "flagEmoji": "🇹🇴" },
    { "name": "Trinidad y Tobago", "flagEmoji": "🇹🇹" },
    { "name": "Túnez", "flagEmoji": "🇹🇳" },
    { "name": "Turkmenistán", "flagEmoji": "🇹🇲" },
    { "name": "Turquía", "flagEmoji": "🇹🇷" },
    { "name": "Tuvalu", "flagEmoji": "🇹🇻" },
    { "name": "Ucrania", "flagEmoji": "🇺🇦" },
    { "name": "Uganda", "flagEmoji": "🇺🇬" },
    { "name": "Uruguay", "flagEmoji": "🇺🇾" },
    { "name": "Uzbekistán", "flagEmoji": "🇺🇿" },
    { "name": "Vanuatu", "flagEmoji": "🇻🇺" },
    { "name": "Vaticano", "flagEmoji": "🇻🇦" },
    { "name": "Venezuela", "flagEmoji": "🇻🇪" },
    { "name": "Vietnam", "flagEmoji": "🇻🇳" },
    { "name": "Wallis y Futuna", "flagEmoji": "🇼🇫" },
    { "name": "Yemen", "flagEmoji": "🇾🇪" },
    { "name": "Yibuti", "flagEmoji": "🇩🇯" },
    { "name": "Zambia", "flagEmoji": "🇿🇲" },
    { "name": "Zimbabue", "flagEmoji": "🇿🇼" }
]
